config/routes.rb
Rails.application.routes.draw do
  resources :destination_foods
  resources :destination_activities
  resources :likes, only: [:show, :create, :index]
  resources :foods, only: [:show, :index]
  resources :activities, only: [:show, :index, :edit, :update]
  resources :destinations, only: [:show, :index]
  resources :login, only: [:new, :create]
  resources :destination_activities

  get '/countries/:name', to: 'countries#show', as: 'countries'
  get '/users/stats', to: 'users#stats', as: 'stats'
  get '/packages/:name', to: 'packages#show', as: 'packages'
  post '/packages/:name', to: 'packages#edit', as: 'edit_packages'
  patch '/packages/:name', to: 'packages#update', as: 'patch_packages'
  
  # root 'hurray#index'
  root to: 'welcome#home', as: 'home'
  resources :users do
    resources :trips, controller: 'users/trips', shallow: true
  end

  post 'activities/:trip', to: 'activities#addactivities', as: 'add_activities'
  post 'destinations/:trip', to: 'destinations#adddestination', as: 'add_destination'

  patch '/activities/:id/dislikes', to: 'activities#dislikes', as: 'dislikes'
  patch '/activities/:id/add_likes', to: 'activities#add_likes', as:'add_likes'

  delete "logout", to: "login#destroy", as: "logout"
  delete "delete", to: "users#destroy", as: "delete"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :trips, dependent: :destroy
    has_many :destinations, through: :trips

    has_many :likes, dependent: :destroy 
    has_many :activities, through: :likes

    validates_presence_of :name, :age
    validates_uniqueness_of :name

    validates :age, numericality: {greater_than: 18}

    has_secure_password 
end

app/controllers/users/trips_controller.rb
require 'net/http'
require 'open-uri'
require 'json'

class Users::TripsController < ApplicationController
    # before_action :find_trip, only: [:edit, :itinerary]

    def show
        # @user = User.find(params[:user_id].to_i)
        @trip = Trip.find(params[:format].to_i)
        if params[:destination]
            @destination = Destination.find(params[:destination_id].to_i)
            @trip.destination = @destination
        else 
            @destination = @trip.destination
        end
    end

    def index 
        @user = User.find(params[:user_id])
        @trips = @user.trips
        if @trips.length == 0
            flash[:errors] = ["No trips to view. Please click on New Trip to create one."]
            redirect_to user_path(@user)
        end
    end 

    def new
        @user = User.find(params[:user_id])
        @trip = @user.trips.new
        @users = User.all
        @destinations = Destination.all
        @destination = Destination.find(params[:destination_id])
        url = "https://pixabay.com/api/?key=20881751-dd7fb42383b27ec4a1d57dca8&q=#{@destination.location}&image_type=photo&pretty=true&safesearch=true&page=1&per_page=6"
        uri = URI.parse(url)
        response = Net::HTTP.get_response(uri)
        response.body
        @image1 = JSON.parse(response.body)["hits"][0]["largeImageURL"]
        @image2 = JSON.parse(response.body)["hits"][1]["largeImageURL"]
        @image3 = JSON.parse(response.body)["hits"][2]["largeImageURL"]
        @image4 = JSON.parse(response.body)["hits"][3]["largeImageURL"]
        @image5 = JSON.parse(response.body)["hits"][4]["largeImageURL"]
        @image6 = JSON.parse(response.body)["hits"][5]["largeImageURL"]
    end 

    def create
        @destination = Destination.find(params["trip"]["destination_id"].to_i)
        @user = User.find(params[:user_id].to_i)
        @trip = Trip.create(start_date: trips_params[:start_date],end_date: trips_params[:end_date],num_of_people: trips_params[:num_of_people], traveller_names: trips_params[:traveller_names], budget:trips_params[:budget],user_id:@user.id, destination_id:@destination.id)
        @trip.save
        redirect_to destination_path(@destination.id,{user_id:@user.id,trip_id:@trip.id})

        # @user = User.find(params[:user_id])
        # @trip = @user.trips.create(trips_params)
        # @user_id = trips_params[:user_id]
        # @destinations = Destination.all

        # if @trip.valid?
        #     redirect_to destinations_path(user_id: @user.id, trip_id: @trip.id)
        # else
        #     flash[:errors] = @trip.errors.full_messages
        #     redirect_to new_user_trip_path(@user)
        # end
    end

    def edit
    end

    def update 
        if params[:id].to_i != 0
            @trip = Trip.find(params[:id])
        else 
            @trip = Trip.find(params["trip"]["trip_id"])
        end 
        @activity = Activity.find(params["trip"]["activity_id"])
        if @activity.trip_id == @trip.id
            @activity.trip_id = 1
            @activity.save
        else 
            @activity.trip_id = @trip.id
            @activity.save
        end
    end

    def destroy
        @trip = @user.trips.find(params[:id])
        @trip.destroy
        render user_trips_path(@user)
    end

    private

    def find_trip
        @trip = @user.trips.find(params[:id])
    end

    def trips_params
        params.require(:trip).permit(:user_id, :end_date, :start_date, :num_of_people, :traveller_names, :budget, :destination_id,:activity,:id)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_login,  :only => [:create, :new]

    def show
        @user_id = @user.id
        @session = 1
        session[:city] = params[:city]
        if session[:city]
            @destinations = Destination.where("location LIKE ?", "%#{session[:city].titleize}%")
            @session = nil
        else
            @destinations = Destination.all.sort_by{|d| d.location}
        end
        @countries = []
        @destinations.each do |d|
            @countries << d.country 
        end
    end

    def handle_city
        if session[:city]
          @destinations = Destination.where("location LIKE ?", "%#{session[:city].titleize}%")
        else
          @destinations = Destination.all
        end
    end    

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(users_params)
        login_user(@user.id)

        if @user.valid?
            redirect_to @user
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path

            #ask about whether you go to the new user or new login
        end
    end

    def edit
    end

    def update
        byebug
        if params[:user][:activity_id].to_i == 0
            redirect_to @user
        else 
            @activity = Activity.find(params[:user][:activity_id])
            @like = Like.where(activity_id: @activity.id, user_id: @user.id)
            @trip = Trip.find(params[:user][:trip_id])
            if @like 
                byebug
                new_like = Like.new
                new_like = Like.create(activity_id: @activity.id, user_id: @user.id)
                new_like.save 
            else 
                Like.find(@like.id).destroy
            end
        end 
    end

    def destroy
        byebug
        @user.destroy
        redirect_to root_path
    end
    
    def stats
    end
private

    def find_user
        @user = User.find(params[:id])
    end

    def users_params
        params.require(:user).permit(:name, :age, :hometown, :username, :password)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with model:@user, method: "PATCH" do |f| %>
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name %><br>

    <%= f.label :age, 'Age:' %>
    <%= f.text_field :age %><br>

    <%= f.label :hometown, 'Hometown:' %>
    <%= f.text_field :hometown %><br>

    <br>
    
    <%= f.submit 'Update Profile', class: 'button3'%>
<% end %>
<%# 
<%= button_to 'Delete User', delete_path(id:@user.id), method: :delete, class: "btn" %> %>

app/views/users/index.html.erb
<% @users.each do |user| %>  
    <p><%= link_to user.name, user %> : <%= link_to "Create Trip", new_user_trip_path(user.id) %></p>
<% end %>
<p><%= link_to "View Site Stats", stats_path %> 

app/views/users/new.html.erb
<%= form_with model:@user do |f| %>

<div class="container" id='home'> 
    <div class="col-sm-6 row g-3" >
        <%= f.label :username, 'Create username:' %>
        <%= f.text_field :username, class: "form-control", placeholder: 'Create Userame' %>
    </div>

    <div class="col-sm-6 row g-3">
        <%= f.label :password, 'Create password:' %>
        <%= f.text_field :password, class: "form-control", placeholder: 'Create Password' %><br>
    </div>

    <div class="col-sm-6 row g-2 col-auto">
        <div class="col-sm">
            <%= f.label :name, 'Name:' %>
            <%= f.text_field :name, class: "form-control", placeholder: 'Enter Name' %>
        </div>

        <div class="col-sm">
            <%= f.label :age, 'Age:' %>
            <%= f.text_field :age, class: "form-control", placeholder: 'Enter Age' %>
        </div>

        <div class="col-sm">
            <%= f.label :hometown, 'Hometown:' %>
            <%= f.text_field :hometown, class: "form-control", placeholder: ' Hometown' %>
        </div>
    </div>
    <br><br><br>

    <div class="col-sm row g-2">
        <%= f.submit 'Complete Sign Up', class: 'btn btn-dark col-6 mx-auto' %>
    </div>

</div>
<% end %>

<br><br><br>

app/views/users/stats.html.erb
<p> Average Trip Budget : $<%=Trip.average_trip_budget%><p>
<p> Average Trip Budgets By Destination : </p>
<% Destination.all.each do |d| %>
    <p><%= d.location %> : $<%= Trip.average_budget_by_destination(d.id) %></p>
<%end%>

<p> 2021 Trips By Month: </p>
<% [1,2,3,4,5,6,7,8,9,10,11,12].each do |mon| %>
<p> Number of trips in <%= Date::MONTHNAMES[mon] %>  : <%= Trip.trip_frequency_by_date(mon) %> </p>
<%end%>

<%= button_to 'Logout', logout_path, method: :delete, class:"button2" %> 
<%= button_to 'Back', :back, class:"button3" %>