config/routes.rb
Rails.application.routes.draw do
  resources :destination_foods
  resources :destination_activities
  resources :likes, only: [:show, :create, :index]
  resources :foods, only: [:show, :index]
  resources :activities, only: [:show, :index, :edit, :update]
  resources :destinations, only: [:show, :index]
  resources :login, only: [:new, :create]
  resources :destination_activities

  get '/countries/:name', to: 'countries#show', as: 'countries'
  get '/users/stats', to: 'users#stats', as: 'stats'
  get '/packages/:name', to: 'packages#show', as: 'packages'
  post '/packages/:name', to: 'packages#edit', as: 'edit_packages'
  patch '/packages/:name', to: 'packages#update', as: 'patch_packages'
  
  # root 'hurray#index'
  root to: 'welcome#home', as: 'home'
  resources :users do
    resources :trips, controller: 'users/trips', shallow: true
  end

  post 'activities/:trip', to: 'activities#addactivities', as: 'add_activities'
  post 'destinations/:trip', to: 'destinations#adddestination', as: 'add_destination'

  patch '/activities/:id/dislikes', to: 'activities#dislikes', as: 'dislikes'
  patch '/activities/:id/add_likes', to: 'activities#add_likes', as:'add_likes'

  delete "logout", to: "login#destroy", as: "logout"
  delete "delete", to: "users#destroy", as: "delete"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :activities
  belongs_to :destination
  validate :trip_date
  validates_presence_of :start_date, :end_date

    def trip_date
        if self.start_date.to_i < DateTime.now.to_i
            errors.add(:start_date, "is in the past. Please input a valid date.")
        end 
    end 

    # def hash_of_activities
    #     hash = {}
    #     if self.activities
    #         self.activities.split(' ').each do |act|
    #             a = Activity.find(act.to_i)
    #             hash[a.name] = Activity.find(act.to_i).price * self.num_of_people
    #         end
    #     end
    #     return hash
    # end

    def total_expense
    #     total = 0
    #     self.hash_of_activities.each do |k, v|
    #         total += v 
    #     end
    #     return total
    end

    def average_trip_time_by_destination
    end

    def self.average_trip_budget
            budgets = Trip.all.map{|t| t.budget}.compact
            if budgets.first
                avg_budget = budgets.sum/budgets.count
            end
    end

    def self.average_budget_by_destination(destination)
        trips = Trip.where(destination_id: destination)
        if trips.first
            budgets = trips.all.map{|t| t.budget}.compact
            avg_budget = budgets.sum/budgets.count
        end
    end

    def self.trip_frequency_by_date(mon)
        dates = Trip.all.map{|t| t.start_date}.compact
        
        case mon
        when 1
            dates.map{|d| d.month if d.month == 1}.compact.count
        when 2
            dates.map{|d| d.month if d.month == 2}.compact.count
        when 3
            dates.map{|d| d.month if d.month == 3}.compact.count
        when 4
            dates.map{|d| d.month if d.month == 4}.compact.count
        when 5
            dates.map{|d| d.month if d.month == 5}.compact.count
        when 6
            dates.map{|d| d.month if d.month == 6}.compact.count
        when 7
            dates.map{|d| d.month if d.month == 7}.compact.count
        when 8
            dates.map{|d| d.month if d.month == 8}.compact.count
        when 9
            dates.map{|d| d.month if d.month == 9}.compact.count
        when 10
            dates.map{|d| d.month if d.month == 10}.compact.count
        when 11
            dates.map{|d| d.month if d.month == 11}.compact.count
        when 12
            dates.map{|d| d.month if d.month == 12}.compact.count
        end

    end

    def self.featured_destinations
        destinations = Trip.all.map{|t| t.destination}.compact 
        dest_count = {}
        destinations.each do |d|
            if not dest_count.key?(d)
                dest_count[d] = destinations.count(d)
            end
        end
        dest_count.sort.to_h.first(4)
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :trips, dependent: :destroy
    has_many :destinations, through: :trips

    has_many :likes, dependent: :destroy 
    has_many :activities, through: :likes

    validates_presence_of :name, :age
    validates_uniqueness_of :name

    validates :age, numericality: {greater_than: 18}

    has_secure_password 
end

app/controllers/users/trips_controller.rb
require 'net/http'
require 'open-uri'
require 'json'

class Users::TripsController < ApplicationController
    # before_action :find_trip, only: [:edit, :itinerary]

    def show
        # @user = User.find(params[:user_id].to_i)
        @trip = Trip.find(params[:format].to_i)
        if params[:destination]
            @destination = Destination.find(params[:destination_id].to_i)
            @trip.destination = @destination
        else 
            @destination = @trip.destination
        end
    end

    def index 
        @user = User.find(params[:user_id])
        @trips = @user.trips
        if @trips.length == 0
            flash[:errors] = ["No trips to view. Please click on New Trip to create one."]
            redirect_to user_path(@user)
        end
    end 

    def new
        @user = User.find(params[:user_id])
        @trip = @user.trips.new
        @users = User.all
        @destinations = Destination.all
        @destination = Destination.find(params[:destination_id])
        url = "https://pixabay.com/api/?key=20881751-dd7fb42383b27ec4a1d57dca8&q=#{@destination.location}&image_type=photo&pretty=true&safesearch=true&page=1&per_page=6"
        uri = URI.parse(url)
        response = Net::HTTP.get_response(uri)
        response.body
        @image1 = JSON.parse(response.body)["hits"][0]["largeImageURL"]
        @image2 = JSON.parse(response.body)["hits"][1]["largeImageURL"]
        @image3 = JSON.parse(response.body)["hits"][2]["largeImageURL"]
        @image4 = JSON.parse(response.body)["hits"][3]["largeImageURL"]
        @image5 = JSON.parse(response.body)["hits"][4]["largeImageURL"]
        @image6 = JSON.parse(response.body)["hits"][5]["largeImageURL"]
    end 

    def create
        @destination = Destination.find(params["trip"]["destination_id"].to_i)
        @user = User.find(params[:user_id].to_i)
        @trip = Trip.create(start_date: trips_params[:start_date],end_date: trips_params[:end_date],num_of_people: trips_params[:num_of_people], traveller_names: trips_params[:traveller_names], budget:trips_params[:budget],user_id:@user.id, destination_id:@destination.id)
        @trip.save
        redirect_to destination_path(@destination.id,{user_id:@user.id,trip_id:@trip.id})

        # @user = User.find(params[:user_id])
        # @trip = @user.trips.create(trips_params)
        # @user_id = trips_params[:user_id]
        # @destinations = Destination.all

        # if @trip.valid?
        #     redirect_to destinations_path(user_id: @user.id, trip_id: @trip.id)
        # else
        #     flash[:errors] = @trip.errors.full_messages
        #     redirect_to new_user_trip_path(@user)
        # end
    end

    def edit
    end

    def update 
        if params[:id].to_i != 0
            @trip = Trip.find(params[:id])
        else 
            @trip = Trip.find(params["trip"]["trip_id"])
        end 
        @activity = Activity.find(params["trip"]["activity_id"])
        if @activity.trip_id == @trip.id
            @activity.trip_id = 1
            @activity.save
        else 
            @activity.trip_id = @trip.id
            @activity.save
        end
    end

    def destroy
        @trip = @user.trips.find(params[:id])
        @trip.destroy
        render user_trips_path(@user)
    end

    private

    def find_trip
        @trip = @user.trips.find(params[:id])
    end

    def trips_params
        params.require(:trip).permit(:user_id, :end_date, :start_date, :num_of_people, :traveller_names, :budget, :destination_id,:activity,:id)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_login,  :only => [:create, :new]

    def show
        @user_id = @user.id
        @session = 1
        session[:city] = params[:city]
        if session[:city]
            @destinations = Destination.where("location LIKE ?", "%#{session[:city].titleize}%")
            @session = nil
        else
            @destinations = Destination.all.sort_by{|d| d.location}
        end
        @countries = []
        @destinations.each do |d|
            @countries << d.country 
        end
    end

    def handle_city
        if session[:city]
          @destinations = Destination.where("location LIKE ?", "%#{session[:city].titleize}%")
        else
          @destinations = Destination.all
        end
    end    

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(users_params)
        login_user(@user.id)

        if @user.valid?
            redirect_to @user
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path

            #ask about whether you go to the new user or new login
        end
    end

    def edit
    end

    def update
        byebug
        if params[:user][:activity_id].to_i == 0
            redirect_to @user
        else 
            @activity = Activity.find(params[:user][:activity_id])
            @like = Like.where(activity_id: @activity.id, user_id: @user.id)
            @trip = Trip.find(params[:user][:trip_id])
            if @like 
                byebug
                new_like = Like.new
                new_like = Like.create(activity_id: @activity.id, user_id: @user.id)
                new_like.save 
            else 
                Like.find(@like.id).destroy
            end
        end 
    end

    def destroy
        byebug
        @user.destroy
        redirect_to root_path
    end
    
    def stats
    end
private

    def find_user
        @user = User.find(params[:id])
    end

    def users_params
        params.require(:user).permit(:name, :age, :hometown, :username, :password)
    end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/trips/_form.html.erb
<%= form_for([@user, @trip]) do |f| %>
    <div class = 'triphome'>
        <%= f.label :start_date, 'Start Date:' %> 
        <%= f.date_field :start_date %> 
        
        <%= f.label :end_date, 'End Date:' %> 
        <%= f.date_field :end_date %><br>

        <%= f.label :num_of_people, 'No. of Total Travellers:' %>
        <%= f.text_field :num_of_people %><br>

        <%= f.label :traveller_names, 'Name of All Travellers:' %>
        <%= f.text_field :traveller_names %><br>

        <%= f.label :budget, 'Budget (in USD):' %>
        <%= f.text_field :budget, :value => '$' %><br>

        <%= f.collection_select :destination_id, @destinations, :id, :country %><br>

        <br>
        <%= f.submit "Continue to Destinations", class:"button3" %>
    <% end %>

    <%= button_to 'Logout', logout_path, method: :delete, class:"button2" %> 
    <%= button_to 'Back', :back, class:"button3" %>
</div>

app/views/users/trips/edit.html.erb
<%= render 'form' %>

app/views/users/trips/index.html.erb
<h1> Your Trips </h1>

<div class="list-group">
<% @user.trips.reverse.each do |trip| %>
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
  <%= link_to "View Trip Details", trip_path(@user,trip) %>
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1"><%= trip.destination.location %></h5>
      <small><%= trip.start_date.strftime("%m/%d/%Y") %> to <%= trip.end_date.strftime("%m/%d/%Y") %>
      </small>
    </div>
    <p class="mb-1">Number of travellers : <%= trip.num_of_people %> , Fellow Travellers : <%= trip.traveller_names %></p>
    <small>Budget : <%= trip.budget%></small>
  </a>
<% end %>
</div>

app/views/users/trips/new.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src=<%= @image1 %> width="500" height="600" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
    <h1>Explore</h1>
    <h1><%= @destination.location %></h1>
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src=<%= @image2 %>  width="500" height="600" alt="Second slide">
       <div class="carousel-caption d-none d-md-block">
    <h1>Explore</h1>
    <h1><%= @destination.location %></h1>
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" width="500" height="600" src=<%= @image3 %> alt="Third slide">
       <div class="carousel-caption d-none d-md-block">
    <h1>Explore</h1>
    <h1><%= @destination.location %></h1>
  </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class = 'triphome'>
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p><%= error %> </p>
    <% end %>
<% end %>

<%= form_for([@user, @trip]) do |f| %>
 
    <%= f.label :date, 'Start Date:' %> 
    <%= f.date_field :start_date %> 
    
    <%= f.label :date, 'End Date:' %> 
    <%= f.date_field :end_date %>

    <%= f.label :num_of_people, 'No. of Travellers:' %>
    <%= f.text_field :num_of_people %><br>

    <%= f.label :traveller_names, 'Name of All Travellers:' %>
    <%= f.text_field :traveller_names %>

    <%= f.label :budget , 'Budget (in USD):' %> 
    <%= f.text_field :budget, :value => '$' %>

    <%# <%= f.collection_select :destination_id, @destinations, :id, :country %>
    <%= f.hidden_field :destination_id, :value => @destination.id %>
    <%# <br> %>
    <%= f.submit "Submit"%>
<% end %>
<br><br><br><br>

<%# <img src=<%= @destination.image %> 
<%# width = 500 height = 400 alt="placeholder 960" opacity=0.1/> %>
</div>

<section class="pt-5 pb-5">
  <div class="container">
    <div class="row">
        <div class="col-6">
            <h3 class="mb-3"> Packages </h3>
        </div>
         <div class="d-flex justify-content-center">
            <a class="btn btn-primary mb-3 mr-1" href="#carouselExampleIndicators3" role="button" data-slide="prev">
                <i class="fa fa-arrow-left"></i>
            </a>&nbsp;
            <a class="btn btn-primary mb-3 " href="#carouselExampleIndicators3" role="button" data-slide="next">
                <i class="fa fa-arrow-right"></i>
            </a>
        </div>
        <div class="col-12">
        <div id="carouselExampleIndicators3" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="row">
                            <div class="col-md-4 mb-3">
                                <div class="card">
                                   <a href="<%= packages_path({:name => @destination.location, :days => "15"}) %>">
                                    <img class="img-fluid" alt="100%x280" src=<%= @image6 %> width:200px>
                                    <div class="card-body">
                                        <h4 class="card-title">15D/14N Package</h4>
                                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <div class="card">
                                <a href="<%= packages_path({:name => @destination.location, :days => "10"}) %>">
                                    <img class="img-fluid" alt="100%x280" src= <%= @image1 %> width:200px>
                                    <div class="card-body">
                                        <h4 class="card-title">10D/9N Package</h4>
                                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                </a>
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <div class="card">
                                <a href="<%= packages_path({:name => @destination.location, :days => "8"}) %>">
                                    <img class="img-fluid" alt="200x280" src=<%= @image4 %> width:200px>
                                    <div class="card-body">
                                        <h4 class="card-title">8D/7N Package</h4>
                                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">

                            <div class="col-md-4 mb-3">
                                <div class="card">
                                <a href="<%= packages_path({:name => @destination.location, :days => "6"}) %>">
                                    <img class="img-fluid" alt="200x280" src=<%= @image3 %> width:200px>
                                    <div class="card-body">
                                        <h4 class="card-title">6D/5N Package</h4>
                                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                </a>
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <div class="card">
                                <a href="<%= packages_path({:name => @destination.location, :days => "5"}) %>">
                                    <img class="img-fluid" alt="200x280" src=<%= @image5 %> width:200px>
                                    <div class="card-body">
                                        <h4 class="card-title">Best of <%= @destination.location %></h4>
                                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                </a>
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <div class="card">
                                <a href="<%= packages_path({:name => @destination.location, :days => "0"}) %>">
                                    <img class="img-fluid" alt="200x280" src=<%= @image2 %>width:200px>
                                    <div class="card-body">
                                        <h4 class="card-title"><%=@destination.location%> Escapade</h4>
                                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>

app/views/users/trips/show.html.erb
<div class = "d-flex justify-content-center">
<%= link_to 'Continue Making Itinerary',destination_path(@trip.destination,trip_id:@trip.id) %> 
&#8287&#8287&#8287
<%= link_to 'View All User Trips', user_trips_path(@user) %>
</div>
<%#
<p><%= link_to image_tag(@trip.destination.image, :size => 500)%>


<% i = 0 %>
<% if @trip.activities %>
<% num = @trip.activities.length %>
<% else %>
<% num = 0 %>
<% end %>
<section id=timeline>
<div class = "d-flex justify-content-center"><%= link_to image_tag(@trip.destination.image, :size => 150)%></div>
	<h1><%= @trip.destination.location%></h1>
	<p class="leader"> Budget : $<%= @trip.budget %></p>
    <p class="leader"> Travel Dates : <%= @trip.start_date.strftime("%m/%d/%Y") %> to <%= @trip.end_date.strftime("%m/%d/%Y") %></p>
	<div class="demo-card-wrapper">
    <% while i < num  do %>
		<div class="demo-card demo-card--step1">
			<div class="head">
				<div class="number-box">
					<span><%= i+1 %></span>
				</div>
				<h2><%= @trip.activities[i].title %></h2>
			</div>
			<div class="body">
				<p><%= @trip.activities[i].text %></p>
				<%= link_to image_tag(@trip.activities[i].img_url, :size => 250), activity_path(@trip.activities[i],@trip) %>
			</div>
		</div>
        <% if @trip.activities.length > i+1 %>
		<div class="demo-card demo-card--step2">
			<div class="head">
				<div class="number-box">
					<span><%= i+2 %></span>
				</div>
				<h2><%= @trip.activities[i+1].title %></h2>
			</div>
			<div class="body">
				<p><%= @trip.activities[i+1].text %></p>
				<%= link_to image_tag(@trip.activities[i+1].img_url, :size => 250), activity_path(@trip.activities[i+1],@trip) %>
			</div>
		</div>
        <% else %>
        <div class="demo-card" id="lol">
			 
		</div>
        <% end %>
         <% if @trip.activities.length > i+2 %>
		<div class="demo-card demo-card--step3">
			<div class="head">
				<div class="number-box">
					<span><%= i+3 %></span>
				</div>
				<h2><%= @trip.activities[i+2].title %></h2>
			</div>
			<div class="body">
				<p> <%= @trip.activities[i+2].text %></p>
				<%= link_to image_tag(@trip.activities[i+2].img_url, :size => 250), activity_path(@trip.activities[i+2],@trip) %>
			</div>
		</div>
        <% else %>
        <div class="demo-card" id="lol">
			
		</div>
        <% end %>
         <% if @trip.activities.length > i+3 %>
		<div class="demo-card demo-card--step4">
			<div class="head">
				<div class="number-box">
					<span><%= i+4 %></span>
				</div>
				<h2><%= @trip.activities[i+3].title %></h2>
			</div>
			<div class="body">
				<p><%= @trip.activities[i+3].text %></p>
				<%= link_to image_tag(@trip.activities[i+3].img_url, :size => 250), activity_path(@trip.activities[i+3],@trip)%>
			</div>
		</div>
        <% else %>
        <div class="demo-card" id="lol">
			
		</div>
        <% end %>
        <% if @trip.activities.length > i+4 %>
		<div class="demo-card demo-card--step5">
			<div class="head">
				<div class="number-box">
					<span><%= i+5 %></span>
				</div>
				<h2><%= @trip.activities[i+4].title %></h2>
			</div>
			<div class="body">
				<p><%= @trip.activities[i+4].text %></p>
				<%= link_to image_tag(@trip.activities[i+4].img_url, :size => 250), activity_path(@trip.activities[i+4],@trip)%>
			</div>
		</div>
        <% else %>
        <div class="demo-card" id="lol">
			
		</div>
        <% end %>
        <% i = i+5 %>
	</div>
    <% end %>
</section>