config/routes.rb
Rails.application.routes.draw do
  resources :destination_foods
  resources :destination_activities
  resources :likes, only: [:show, :create, :index]
  resources :foods, only: [:show, :index]
  resources :activities, only: [:show, :index, :edit, :update]
  resources :destinations, only: [:show, :index]
  resources :login, only: [:new, :create]
  resources :destination_activities

  get '/countries/:name', to: 'countries#show', as: 'countries'
  get '/users/stats', to: 'users#stats', as: 'stats'
  get '/packages/:name', to: 'packages#show', as: 'packages'
  post '/packages/:name', to: 'packages#edit', as: 'edit_packages'
  patch '/packages/:name', to: 'packages#update', as: 'patch_packages'
  
  # root 'hurray#index'
  root to: 'welcome#home', as: 'home'
  resources :users do
    resources :trips, controller: 'users/trips', shallow: true
  end

  post 'activities/:trip', to: 'activities#addactivities', as: 'add_activities'
  post 'destinations/:trip', to: 'destinations#adddestination', as: 'add_destination'

  patch '/activities/:id/dislikes', to: 'activities#dislikes', as: 'dislikes'
  patch '/activities/:id/add_likes', to: 'activities#add_likes', as:'add_likes'

  delete "logout", to: "login#destroy", as: "logout"
  delete "delete", to: "users#destroy", as: "delete"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :trip
  has_many :likes, dependent: :destroy 
  has_many :users, through: :likes
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

    @@mapping = {}

    def show      
        if params[:id].to_i != 0
            @activity = Activity.find(params[:id])
            if params[:format].to_i != 0
                @trip = Trip.find(params[:format])
            else
                @trip = Trip.find(params[:user][:trip_id])
            end
        else
            @trips = Trip.all
            if params[:trip_id].to_i != 0
                @trip = Trip.find(params[:trip_id])
                @trip_id = params[:trip_id]  
            end 
            @title = params["value"][0]["title"]
            @activity = Activity.find_by(title: @title)
        end
    end 

    def index 
        @trip = Trip.find(params[:id])
        @destination = @trip.destination
        @type = params[:type] 
        if @@mapping.key?(@destination.location+"-"+@type)
            @places = @@mapping[@destination.location+"-"+@type]
        else 
            @places = Getdatum.get_places(@destination.lat,@destination.lon,@type)
            @places.each do |place,value|
                @img_url = value[0]["source"]
                @text = value[2]["text"]
                @title = value[2]["title"]
                @house = value[1]["house"] || ""
                @road = value[1]["road"] || ""
                @town = value[1]["town"] || ""
                @state = value[1]["state"] || ""
                @county = value[1]["county"] || ""
                @suburb = value[1]["suburb"] || ""
                @country = value[1]["country"] || ""
                @postcode = value[1]["postcode"] || ""
                @address = @house + ", "+ @road +", "+ @town +", " + @state +", "+ @county +", "+ @suburb +", "+ @country+", " + @postcode
                results = Geocoder.search(@house + ", "+ @road +", "+ @town +", " + @state +", "+ @county +", "+ @suburb +", "+ @country)
                if results.first
                    @lat = results.first.coordinates[0]
                    @lng = results.first.coordinates[1]
                end 
                @search_activity = Activity.find_by(address: @address)
                if !@search_activity
                    @activity = Activity.new 
                    @activity = Activity.create(title: @title, img_url: @img_url,text: @text, address: @address, lat: @lat, lng: @lng) 
                    @activity.trip_id = 1
                    @activity.save 
                    @dest_act = DestinationActivity.new
                    @dest_act = DestinationActivity.create(destination_id: @destination.id, activity_id: @activity.id)
                end 
            end
            @@mapping[@destination.location+"-"+@type] = @places 
        end
    end

    def addactivities
        @trip = Trip.find(params[:trip].to_i)
        @activity = Activity.find(params[:activity].to_i)
        @user = @trip.user
        if @trip.activities == nil 
            # @trip.activities == @activity.name
            # @trip.save
            @trip.update_attribute(:activities, @activity.id.to_s)
        else
            @activities = @trip.activities + " " + @activity.id.to_s
            @trip.update_attribute(:activities, @activities )
        end
        redirect_to user_trip_path(@user,@trip)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/index.html.erb
<div>
<h2 class = "dest_name"><%= @type.capitalize %><h2>

<p>
<% @places.each do |place,value| %>
<div class="content">
  <div class="grid">
    <figure class="effect-lily">
      <%= link_to image_tag(value[0]["source"], :size => 249),
 activity_path(place,{value:value, trip_id: @trip.id}) %>
      <figcaption>
        <div>
          <h2><%= place %></h2> 
        </div>
         <%= link_to image_tag(value[0]["source"]),activity_path(place,{value:value, trip_id: @trip.id})  %>
      </figcaption>			
    </figure>
  </div>
<%end%>
</div>.
<p>
<br><br><br><br><br><br><br><br>

app/views/activities/show.html.erb
<div style ="text-align:center">
<br><br>
<%= link_to 'Continue Making Itinerary',destination_path(@trip.destination,trip_id:@trip.id) %> 
<%= link_to 'View Itinerary',trip_path(@user,@trip) %> 
<h3><%= @title %></h3>
<br>
<%= link_to image_tag(@activity.img_url, :size => 500)%>
<br><br>

<%= form_for(@trip) do |f| %>
    <%= f.hidden_field :trip_id, :value => @trip_id %>
    <%= f.hidden_field :activity_id, :value => @activity.id %>
    <button id="btn2" onclick="myFunction()"> 
    <% if @activity.trip_id != @trip.id %>
    Add To Itinerary
    <% else %>
    Added To Itinerary
    <% end %>
    </button>
    <%= f.submit "❤️" %>
<% end %>

<%# <%= form_for(@user) do |f| %>
    <%# <%= f.hidden_field :trip_id, :value => @trip_id %>
    <%# <%= f.hidden_field :activity_id, :value => @activity.id %> 
    <%# <button id="btn1" onclick="myFunction2()"> Like <%= f.submit "+" %>
    <%# </button> %>
<%# <% end %> 

<script>
  function myFunction() {
      var change = document.getElementById("btn2");
      if (change.innerText == "Added To Itinerary")
      {
          change.innerText = "Add To Itinerary";
      }
      else {
          change.innerText = "Added To Itinerary";
      }
  }

    function myFunction2() {
      var change = document.getElementById("btn1");
      if (change.innerHTML == "Like")
      {
          change.innerHTML = "Liked";
      }
      else {
          change.innerHTML = "Like";
      }
  }

</script>

<br><br>
<h5><%= @activity.text %></h5>
<br><br>
<h5>Address : <%= @activity.address %></h5><br><br>
<h5>How To Get There?</h5>
 <iframe width="100%" 
  height="500" 
  frameborder="0" 
  scrolling="no" 
  marginheight="0" 
  marginwidth="0"  src="https://www.google.com/maps/embed/v1/place?q=<%=@activity.lat%>,<%=@activity.lng%>&amp;key=AIzaSyBAeaMywiXmsyhhPIabeTCZxBq6FqLAGWU"></iframe>
 
</div>
<br><br>
<br><br>